apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: ingress-nginx
spec:
  replicas: 1 # TODO: pass as parameter the number of replicas as needed
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec: 
      containers:
      - name: sample-app
      # TODO: remove hard coded iage
        image: 300359003805.dkr.ecr.us-east-2.amazonaws.com/sample_cndp_v2_template:latest
        ports:
        - name: http
          containerPort: 8080
