apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: ingress-nginx
spec:
  selector:
    app: sample-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
